name: 'MyBills'

services:
  db:
    container_name: db
    image: postgres:18
    ports:
      - '${DB_PORT-5432}:5432'
    volumes:
      - mybills-db-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  mybills-db-data:
